### ISSUE TITLE
Glow not working with latest web-sys (0.3.89)

### ISSUE THREAD

**Issue by oscargus** [grovesNL/glow#356]
Seems like these functions are no longer exported or has been removed as they were in the unstable API. There are more functions than this, but all similar error messages.
```
error[E0599]: no method named `tex_image_2d_with_u32_and_u32_and_video_frame` found for reference `&WebGlRenderingContext` in the current scope
   --> /builds/surfer-project/surfer/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/glow-0.16.0/src/web_sys.rs:610:20
    |
610 |                 gl.tex_image_2d_with_u32_and_u32_and_video_frame(
    |                 ---^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
help: there is a method `tex_image_2d_with_u32_and_u32_and_video` with a similar name
    |
610 -                 gl.tex_image_2d_with_u32_and_u32_and_video_frame(
610 +                 gl.tex_image_2d_with_u32_and_u32_and_video(
```

**Comment by oscargus** [comment]
Fixed in web-sys 0.3.90
